### ISSUE TITLE
Replace udem-dlteam/gambit with a fork of gambit/gambit

### ISSUE THREAD

**Issue by lassik** [udem-dlteam/gambit-deprecated#17]
Currently GitHub doesn't think this repo is a fork of https://github.com/gambit/gambit so there isn't an easy way to send pull requests from this repo to Gambit's main repo.

Could we delete this repo and then recreate it as a GitHub fork of gambit/gambit?

Note that forks don't have their own issue tracker, so we'd have to discuss issues in the main gambit/gambit issue tracker. Personally I think it would be an improvement to have all issues gathered in the same place now that both repos are public.

**Comment by lassik** [comment]
(I checked, and GitHub doesn't have a way to retroactively turn a repo into a fork of another.)

**Comment by lassik** [comment]
@feeley What do you think about this?

**Comment by feeley** [comment]
Yes I think that is good idea.

**Comment by lassik** [comment]
I saved the `lassik/cirrus` branch under my personal clone of gambit. The `cpu` and `geiser` branches in this repo still have commits that have not been merged into the official gambit repo.

**Comment by abdelq** [comment]
@lassik not the case for `cpu`, `geiser` maybe.

**Comment by feeley** [comment]
The repo has now been renamed to gambit-deprecated (just in case... we can remove it later) and a fork of gambit/gambit has been created.

**Comment by lassik** [comment]
Thank you!

**Comment by lassik** [comment]
I no longer have push permissions to the new fork. I can also use my personal fork or send PRs to gambit/gambit.

**Comment by feeley** [comment]
You should be back in business now.

**Comment by lassik** [comment]
It works. Thank you!

**Comment by lassik** [comment]
I'm closing this issue as there are no problems with the new repo. I deleted the `lassik/cirrus` branch from this deprecated repo.
